spring:
  application:
    name: task-management-system
  profiles:
    default: local

app:
  security:
    jwt:
      secret: ${JWT_SECRET:replace_this_with_at_least_32_characters_secret}
      access-token-expiration-seconds: ${JWT_ACCESS_EXPIRATION_SECONDS:900}
      refresh-token-expiration-seconds: ${JWT_REFRESH_EXPIRATION_SECONDS:604800}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
